/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/osgeo/gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
Testing pre-trained model on latest Monsoon season...
Grabbing testing data...
Predicting on 2024 Monsoon season...
length of test dataset is: 18
> /Users/kelseydoerksen/code/landslide-forecast-nepal/unet/dataset.py(93)__getitem__()
     92
---> 93         image_fn = image_fns[index]
     94         label_fn = label_fns[index]
['label_2024-04-14.npy', 'label_2024-04-15.npy', 'label_2024-04-16.npy', 'label_2024-04-17.npy', 'label_2024-04-18.npy', 'label_2024-04-19.npy', 'label_2024-04-20.npy', 'label_2024-04-21.npy', 'label_2024-04-22.npy', 'label_2024-04-23.npy', 'label_2024-04-24.npy', 'label_2024-04-25.npy', 'label_2024-04-26.npy', 'label_2024-04-27.npy', 'label_2024-04-28.npy', 'label_2024-04-29.npy', 'label_2024-04-30.npy', 'label_2024-05-01.npy', 'label_2024-05-02.npy', 'label_2024-05-03.npy', 'label_2024-05-04.npy', 'label_2024-05-05.npy', 'label_2024-05-06.npy', 'label_2024-05-07.npy', 'label_2024-05-08.npy', 'label_2024-05-09.npy', 'label_2024-05-10.npy', 'label_2024-05-11.npy', 'label_2024-05-12.npy', 'label_2024-05-13.npy', 'label_2024-05-14.npy', 'label_2024-05-15.npy', 'label_2024-05-16.npy', 'label_2024-05-17.npy', 'label_2024-05-18.npy', 'label_2024-05-19.npy', 'label_2024-05-20.npy', 'label_2024-05-21.npy', 'label_2024-05-22.npy', 'label_2024-05-23.npy', 'label_2024-05-24.npy', 'label_2024-05-25.npy', 'label_2024-05-26.npy', 'label_2024-05-27.npy', 'label_2024-05-28.npy', 'label_2024-05-29.npy', 'label_2024-05-30.npy', 'label_2024-05-31.npy', 'label_2024-06-01.npy', 'label_2024-06-02.npy', 'label_2024-06-03.npy', 'label_2024-06-04.npy', 'label_2024-06-05.npy', 'label_2024-06-06.npy', 'label_2024-06-07.npy', 'label_2024-06-08.npy', 'label_2024-06-09.npy', 'label_2024-06-10.npy', 'label_2024-06-11.npy', 'label_2024-06-12.npy', 'label_2024-06-13.npy', 'label_2024-06-14.npy', 'label_2024-06-15.npy', 'label_2024-06-16.npy', 'label_2024-06-17.npy', 'label_2024-06-18.npy', 'label_2024-06-19.npy', 'label_2024-06-20.npy', 'label_2024-06-21.npy', 'label_2024-06-22.npy', 'label_2024-06-23.npy', 'label_2024-06-24.npy', 'label_2024-06-25.npy', 'label_2024-06-26.npy', 'label_2024-06-27.npy', 'label_2024-06-28.npy', 'label_2024-06-29.npy', 'label_2024-06-30.npy', 'label_2024-07-01.npy', 'label_2024-07-02.npy', 'label_2024-07-03.npy', 'label_2024-07-04.npy', 'label_2024-07-05.npy', 'label_2024-07-06.npy', 'label_2024-07-07.npy', 'label_2024-07-08.npy', 'label_2024-07-09.npy', 'label_2024-07-10.npy', 'label_2024-07-11.npy', 'label_2024-07-12.npy', 'label_2024-07-13.npy', 'label_2024-07-14.npy', 'label_2024-07-15.npy', 'label_2024-07-16.npy', 'label_2024-07-17.npy', 'label_2024-07-18.npy', 'label_2024-07-19.npy', 'label_2024-07-20.npy', 'label_2024-07-21.npy', 'label_2024-07-22.npy', 'label_2024-07-23.npy', 'label_2024-07-24.npy', 'label_2024-07-25.npy', 'label_2024-07-26.npy', 'label_2024-07-27.npy', 'label_2024-07-28.npy', 'label_2024-07-29.npy', 'label_2024-07-30.npy', 'label_2024-07-31.npy', 'label_2024-08-01.npy', 'label_2024-08-02.npy', 'label_2024-08-03.npy', 'label_2024-08-04.npy', 'label_2024-08-05.npy', 'label_2024-08-06.npy', 'label_2024-08-07.npy', 'label_2024-08-08.npy', 'label_2024-08-09.npy', 'label_2024-08-10.npy', 'label_2024-08-11.npy', 'label_2024-08-12.npy', 'label_2024-08-13.npy', 'label_2024-08-14.npy', 'label_2024-08-15.npy', 'label_2024-08-16.npy', 'label_2024-08-17.npy', 'label_2024-08-18.npy', 'label_2024-08-19.npy', 'label_2024-08-20.npy', 'label_2024-08-21.npy', 'label_2024-08-22.npy', 'label_2024-08-23.npy', 'label_2024-08-24.npy', 'label_2024-08-25.npy', 'label_2024-08-26.npy', 'label_2024-08-27.npy', 'label_2024-08-28.npy', 'label_2024-08-29.npy', 'label_2024-08-30.npy', 'label_2024-08-31.npy', 'label_2024-09-01.npy', 'label_2024-09-02.npy', 'label_2024-09-03.npy', 'label_2024-09-04.npy', 'label_2024-09-05.npy', 'label_2024-09-06.npy', 'label_2024-09-07.npy', 'label_2024-09-08.npy', 'label_2024-09-09.npy', 'label_2024-09-10.npy', 'label_2024-09-11.npy', 'label_2024-09-12.npy', 'label_2024-09-13.npy', 'label_2024-09-14.npy', 'label_2024-09-15.npy', 'label_2024-09-16.npy', 'label_2024-09-17.npy', 'label_2024-09-18.npy', 'label_2024-09-19.npy', 'label_2024-09-20.npy', 'label_2024-09-21.npy', 'label_2024-09-22.npy', 'label_2024-09-23.npy', 'label_2024-09-24.npy', 'label_2024-09-25.npy', 'label_2024-09-26.npy', 'label_2024-09-27.npy', 'label_2024-09-28.npy', 'label_2024-09-29.npy', 'label_2024-09-30.npy', 'label_2024-10-01.npy']
0
(60, 100)
<matplotlib.image.AxesImage object at 0x12314e1a0>
'/Volumes/PRO-G40/landslides/Nepal_Landslides_Forecasting_Project/Monsoon2024_Prep/2024_Season_Retro/Binary_Landslide_Labels_14day'
'/Volumes/PRO-G40/landslides/Nepal_Landslides_Forecasting_Project/Monsoon2024_Prep/2024_Season_Retro/Binary_Landslide_Labels_14day/label_2024-04-14.npy'
*** NameError: name 'np' is not defined
<matplotlib.image.AxesImage object at 0x14c9d6fe0>
<matplotlib.image.AxesImage object at 0x14bf8cb50>
'/Volumes/PRO-G40/landslides/Nepal_Landslides_Forecasting_Project/Monsoon2024_Prep/2024_Season_Retro/Binary_Landslide_Labels_14day/label_2024-04-14.npy'
<matplotlib.image.AxesImage object at 0x14c005f30>
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/run_pipeline.py", line 149, in <module>
    predict(unet, landslide_test_dataset, experiment, save_dir, device=device,
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/predict.py", line 46, in predict
    for i, data in enumerate(test_loader):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/dataset.py", line 93, in __getitem__
    label_fn = label_fns[index]
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/dataset.py", line 93, in __getitem__
    label_fn = label_fns[index]
  File "/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True