Testing pre-trained model on latest Monsoon season...
Grabbing testing data...
Predicting on 2024 Monsoon season...
length of test dataset is: 18
/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/osgeo/gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
test set BCE is: 0.08715043216943741