Testing pre-trained model on latest Monsoon season...
Grabbing testing data...
Predicting on 2024 Monsoon season...
/Users/kelseydoerksen/opt/anaconda3/envs/aq/lib/python3.10/site-packages/osgeo/gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/run_pipeline.py", line 146, in <module>
    predict(unet, landslide_test_dataset, experiment, save_dir, device=device,
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/predict.py", line 65, in predict
    print('test set BCE is: {}'.format(bce_score / len(test_loader)))
ZeroDivisionError: division by zero